name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Build for amd64
      run: GOOS=linux GOARCH=amd64 go build -o app-amd64 main.go

    - name: Build for arm64
      run: GOOS=linux GOARCH=arm64 go build -o app-arm64 main.go

    - name: Build for windows64
      run: GOOS=windows GOARCH=amd64 go build -o app-windows64.exe main.go
    - name: Run UPX
      uses: crazy-max/ghaction-upx@v2
      with:
          version: latest
          files: |
            ./app-*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./app-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
